### ISSUE TITLE
No fans and no filament

### ISSUE THREAD

**Issue by thilbig** [iceananas/Marlin-1.1.9-for-Anycubic-4Max-with-TMC2208#1]
If I compile your firmware and upload it to my Anycubic 4Max the controller fan didn't start and no filament comes out of the nozzle when I print. What's going wrong?

Regards
Thomas

**Comment by iceananas** [comment]
- Controller fan:

The fan will only activate if a stepper driver or a heating element is in use. 
If this is not the case, find this section in `Configuration_adv.h`:

```
#define USE_CONTROLLER_FAN
#if ENABLED(USE_CONTROLLER_FAN)
  #define CONTROLLER_FAN_PIN 7           // Set a custom pin for the controller fan
  #define CONTROLLERFAN_SECS 60          // Duration in seconds for the fan to run after all motors are disabled
  #define CONTROLLERFAN_SPEED 127        // 255 == full speed
#endif
```

and set `CONTROLLERFAN_SPEED``to 255. Probably the fan does not turn on with half speed PWM. 

If that doesn't help, make sure that the controller fan is connected to the right port. You can find the pin mapping [here](https://www.thingiverse.com/thing:2485534/files).

- Extruder:

Is your extruder not turning at all? How much current did you set for the extruder? I had to set my TMC2208 to 0.9A-1A to extrude reliably (while 0.7 enough for the axis).

Also, there is a mininum extrusion temperature set in `Configuration.h`. To disable or modify this feature, find the lines:

```
#define PREVENT_COLD_EXTRUSION
#define EXTRUDE_MINTEMP 170
```

Hope that helps :)

**Comment by thilbig** [comment]
Many thanks. Now it's working. I've set the speed to 255. All other worked out of the box.
